title = "CanaryEngine"
gitRepoUrl = "https://github.com/canary-development/CanaryEngine"
gitSourceBranch = "main"

changelog = true

apiCategories = [
    "Event"
]

[navbar.logo]
alt = "CanaryEngine"
src = "navbar.png"

[[navbar.items]]
href = "https://discord.gg/cwwcZtqJAt"
label = "Discord"
position = "right"

[[navbar.items]]
href = "https://trello.com/b/fTJOmMua/canaryengine"
label = "Trello"
position = "right"

[[classOrder]]
section = "ğŸ•¹ Framework API"
collapsed = true
classes = ["CanaryEngine", "CanaryEngineServer", "CanaryEngineClient", "CanaryEngineReplicated"]

[[classOrder]]
section = "ğŸ–¥ Networking API"
collapsed = true
classes = ["NetworkControllerServer", "NetworkControllerClient"]

[[classOrder]]
section = "ğŸ“¢ Signal API"
collapsed = true
classes = ["SignalControllerObject"]

[[classOrder]]
section = "ğŸ’¾ Data API"
collapsed = true
classes = ["EasyProfile", "ProfileStoreObject", "ProfileObject"]

[[classOrder]]
section = "ğŸ§± Engine API"
collapsed = true
classes = ["EngineLoader", "EngineDebugger", "EngineTypes"]

[[classOrder]]
section = "â² Benchmark API"
collapsed = true
classes = ["Benchmark", "BenchmarkObject"]

[[classOrder]]
section = "ğŸ“¦ Library API"
collapsed = true
classes = ["Sprite", "Base64", "Statistics", "Utility", "Fetch", "UIShelf"]

[[classOrder]]
section = "ğŸ’¬ API Objects"
collapsed = true
classes = ["TopBarIconObject", "TopBarSpacerObject"]

[docusaurus]
projectName = "CanaryEngine"
tagline = "The lightweight and optimized framework"
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = "favicon.png"

[footer]
style = "dark"
copyright = "Copyright Â© 2023 canary. Built with Moonwave"

[home]
enabled = true
includeReadme = false

[[home.features]]
title = "Type Safe ğŸ¦º"
description = "Strictly typed, along with native support for roblox-ts that can be found on the NPM marketplace."

[[home.features]]
title = "Secure ğŸ”"
description = "The networking system that CanaryEngine uses can actually partially prevent exploits like RemoteSpy from being easily useable."

[[home.features]]
title = "Optimized ğŸƒâ€â™€ï¸"
description = "Extremely optimized, with most internal functions running fast along with custom signal and network implementations."